name: npm scripts

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm run build
    - run: npm test
